server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: shramii-hiring-platform
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/shramii_hiring
      auto-index-creation: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:shramii-super-secret-key-for-jwt-token-generation}
  expiration: 86400000 # 24 hours in milliseconds

file:
  upload:
    dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10MB

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.shramii: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/shramii.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
